# Generated by Django 4.2.1 on 2023-05-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField()),
                ('player_name', models.TextField()),
                ('time_frame', models.TextField()),
                ('points', models.FloatField()),
                ('ast', models.FloatField()),
                ('reb', models.FloatField()),
                ('pie', models.FloatField()),
            ],
        ),
    ]
