# Generated by Django 4.2.1 on 2023-08-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_register', '0002_players_player_imgurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='ast',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='pie',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='player_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='player_imgurl',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='player_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='points',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='reb',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='time_frame',
            field=models.TextField(null=True),
        ),
    ]
